name: scube_task_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# dependency for production
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  logger: ^2.6.2
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  get_it: ^9.2.0
  syncfusion_flutter_gauges: ^32.1.19

# dependency for dev
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

